<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="pi_robot">

  <!-- Constants -->
  <xacro:property name="base_radius" value="0.1" />
  <xacro:property name="base_height" value="0.05" />
  <xacro:property name="wheel_radius" value="0.033" />
  <xacro:property name="wheel_width" value="0.02" />
  <xacro:property name="wheel_base" value="0.16" />
  <xacro:property name="caster_radius" value="0.015" />

  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
      <material name="blue">
        <color rgba="0.0 0.0 1.0 1.0" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_height}" />
      </geometry>
    </collision>
  </link>

  <!-- Right Wheel -->
  <link name="right_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <material name="black">
        <color rgba="0.0 0.0 0.0 1.0" />
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="right_wheel_link" />
    <origin xyz="0 -${wheel_base/2} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Left Wheel -->
  <link name="left_wheel_link">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
      <material name="black" />
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}" />
      </geometry>
      <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
    </collision>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link" />
    <child link="left_wheel_link" />
    <origin xyz="0 ${wheel_base/2} 0" rpy="0 0 0" />
    <axis xyz="0 1 0" />
  </joint>

  <!-- Caster Wheel -->
  <link name="caster_link">
    <visual>
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0" />
      </material>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${caster_radius}" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_joint" type="fixed">
    <parent link="base_link" />
    <child link="caster_link" />
    <origin xyz="${base_radius * 0.8} 0 -${base_height/2 - caster_radius}" rpy="0 0 0" />
  </joint>

  <!-- Camera -->
  <link name="camera_link">
    <visual>
      <geometry>
        <box size="0.02 0.05 0.05" />
      </geometry>
      <material name="red">
        <color rgba="1.0 0.0 0.0 1.0" />
      </material>
    </visual>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link" />
    <child link="camera_link" />
    <origin xyz="${base_radius} 0 0" rpy="0 0 0" />
  </joint>

  <!-- Gazebo Plugins -->
  <gazebo>
    <plugin name="diff_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <ros>
        <namespace>/</namespace>
      </ros>
      <left_joint>left_wheel_joint</left_joint>
      <right_joint>right_wheel_joint</right_joint>
      <wheel_separation>${wheel_base}</wheel_separation>
      <wheel_diameter>${2 * wheel_radius}</wheel_diameter>
      <max_wheel_torque>20</max_wheel_torque>
      <max_wheel_acceleration>1.0</max_wheel_acceleration>
      <command_topic>cmd_vel</command_topic>
      <publish_odom>true</publish_odom>
      <publish_odom_tf>true</publish_odom_tf>
      <publish_wheel_tf>true</publish_wheel_tf>
      <odometry_frame>odom</odometry_frame>
      <robot_base_frame>base_link</robot_base_frame>
    </plugin>

    <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
        <ros>
            <namespace>/</namespace>
        </ros>
        <camera_name>pi_camera</camera_name>
        <frame_name>camera_link</frame_name>
        <hack_baseline>0.0</hack_baseline>
        <min_update_rate>10.0</min_update_rate>
        <image_topic_name>image_raw</image_topic_name>
        <camera_info_topic_name>camera_info</camera_info_topic_name>
    </plugin>
  </gazebo>

</robot>
